study_bud/core/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.get_routes),
    path("rooms/", views.get_rooms),
    path("room/<int:id>", views.get_room),
]

study_bud/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login", views.sign_in, name="login"),
    path("logout", views.log_out, name="logout"),
    path("register", views.sign_up, name="register"),
    path("user/<int:pk>", views.user_profile, name="user-profile"),
    path("user/edit", views.edit_user, name="user-edit"),
    path("room/<int:pk>", views.room, name="room"),
    path("room/new", views.create_room, name="create-room"),
    path("room/<int:pk>/", views.edit_room, name="edit-room"),
    path("room/<int:pk>/delete/", views.delete_room, name="delete-room"),
    path("message/<int:pk>/delete/", views.delete_message, name="delete-message"),
]

study_bud/study_bud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("core.api.urls")),
]

study_bud/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name="participants", blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return str(self.name)


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.body[:50]

study_bud/core/forms.py
from django.forms import ModelForm
from .models import Room
from django.contrib.auth.models import User


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = "__all__"
        exclude = ["host", "participants"]


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email"]

study_bud/core/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from core.models import Room
from .serializers import RoomSerializer


@api_view(["GET"])
def get_routes(request):
    routes = ["GET /api/rooms", "GET /api/rooms/:id"]
    return Response(routes)


@api_view(["GET"])
def get_rooms(request):
    rooms = Room.objects.all()
    serialiazer = RoomSerializer(rooms, many=True)
    return Response(serialiazer.data)


@api_view(["GET"])
def get_room(request, id):
    rooms = Room.objects.get(id=id)
    serialiazer = RoomSerializer(rooms, many=False)
    return Response(serialiazer.data)

study_bud/core/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Room, Topic, Message
from .forms import RoomForm
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .forms import UserForm

# Create your views here.


def home(request):
    q = request.GET.get("q", "")
    rooms = Room.objects.all()
    topics = Topic.objects.all()
    if q:
        rooms = rooms.filter(
            Q(topic__name__icontains=q)
            | Q(name__icontains=q)
            | Q(description__icontains=q)
        )
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    rooms_count = rooms.count()
    context = {
        "rooms": rooms,
        "topics": topics,
        "rooms_count": rooms_count,
        "room_messages": room_messages,
    }
    return render(request, "core/home.html", context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all().order_by("-created")
    if request.method == "POST":
        room_messages = Message.objects.create(
            user=request.user, room=room, body=request.POST.get("body")
        )
        room.participants.add(request.user)
        return redirect("core:room", pk=room.id)
    participants = room.participants.all()
    context = {
        "room": room,
        "room_messages": room_messages,
        "participants": participants,
    }
    return render(request, "core/room.html", context)


@login_required(login_url="core:login")
def create_room(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == "POST":
        topic_name = request.POST.get("topic")
        topic = Topic.objects.get_or_create(name=topic_name)
        Room.objects.create(
            host=request.user,
            name=request.POST.get("name"),
            description=request.POST.get("description"),
            topic=topic,
        )

        return redirect("core:home")

    context = {"form": form, "topics": topics}
    return render(request, "core/room_form.html", context)


@login_required(login_url="core:login")
def edit_room(request, pk):
    room = Room.objects.get(id=pk)
    topics = Topic.objects.all()
    form = RoomForm(instance=room)

    if request.user != room.host:
        return HttpResponse("Your are not allowed ")
    if request.method == "POST":
        topic_name = request.POST.get("topic")
        topic = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get("name")
        room.topic = topic
        room.description = request.POST.get("description")
        room.save()
        return redirect("core:home")
    context = {"form": form, "topics": topics, "room": room}
    return render(request, "core/room_form.html", context)


@login_required(login_url="core:login")
def delete_room(request, pk):
    room = Room.objects.get(id=pk)
    if request.user != room.host:
        return HttpResponse("Your are not allowed ")
    if request.method == "POST":
        room.delete()
        return redirect("core:home")
    return render(request, "core/delete.html", {"obj": room})


def sign_in(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("core:home")
    if request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("core:home")
        else:
            messages.error(request, "Username or Password does not exist")
    context = {"page": page}
    return render(request, "core/login_register.html", context)


def sign_up(request):
    page = "register"
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect("core:home")
        else:
            messages.error(
                request,
                "Le mot de passe doit comporter une minuscule, une majuscule et des chiffres(taille entier sup 6 caractères)",
            )
    context = {"form": form}
    return render(request, "core/login_register.html", context)


def log_out(request):
    logout(request)
    return redirect("core:home")


@login_required(login_url="core:login")
def delete_message(request, pk):
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        return HttpResponse("Your are not allowed ")
    if request.method == "POST":
        message.delete()
        return redirect("core:home")
    return render(request, "core/delete.html", {"obj": message})


def user_profile(request, pk):
    user = User.objects.get(id=pk)
    topics = Topic.objects.all()
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    context = {
        "user": user,
        "rooms": rooms,
        "room_messages": room_messages,
        "topics": topics,
    }
    return render(request, "core/profile.html", context)


@login_required(login_url="core:login")
def edit_user(request):
    form = UserForm(instance=request.user)
    if request.method == "POST":
        form = UserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("core:home")
    context = {"form": form}
    return render(request, "core/edit-user.html", context)

study_bud/core/templates/core/activity_component.html
<!-- Activities Start -->
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages  %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'core:user-profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="https://randomuser.me/api/portraits/women/11.jpg" />
          </div>
          <p>
            @{{message.user}}
            <span>{{message.created|timesince}} days ago</span>
          </p>
        </a>
        {% if request.user == message.user %}
        <div class="roomListRoom__actions">
          <a href="{% url 'core:delete-message' message.id%}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'core:room' message.room.id%}">{{message.room.name}}</a>”</p>
        <div class="activities__boxRoomContent">
         {{message.body}}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- Activities End -->
   
</div>

study_bud/core/templates/core/edit-user.html
{% extends 'main.html'%};
{% block content %}
    

<main class="update-account layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{% url 'core:user-profile' request.user.id%}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Edit your profile</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form__group">
                            <label for="profile_{{field.label}}">{{field.label}}</label>
                            {{field}}
                        </div>
                    {% endfor %}

                    <div class="form__action">
                        <a class="btn btn--dark" href="{% url 'core:home' %}">Cancel</a>
                        <button class="btn btn--main" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </div>
</main>

{% endblock %}

study_bud/core/templates/core/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'core:user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" />
        </div>
        <span>@{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created | timesince }} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'core:room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'core:room' room.id %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{room.participants.all.count}} Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
  </div>
{% endfor %}

study_bud/core/templates/core/home.html
{% extends 'main.html'%};
{% block content %}
<main class="layout layout--3">
    <div class="container">
      {% include 'core/topics_component.html'%}

      <!-- Room List Start -->
      <div class="roomList">
        <div class="mobile-menu">
          <form method="get" action="{% url 'core:home'%}" class="header__search">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input name="q" placeholder="Search for posts" />
            </label>
          </form>
          <div class="mobile-menuItems">
            <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
            <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
          </div>
        </div>
        <div class="roomList__header">
          <div>
            <h2>Study Room</h2>
            <p>{{rooms_count}} Rooms available</p>
          </div>
          <a class="btn btn--main" href="{% url 'core:create-room' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>add</title>
              <path
                d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
              ></path>
            </svg>
            Create Room
          </a>
        </div>
        {% include 'core/feed_component.html' %}
  
      </div>
      <!-- Room List End -->

      {% include 'core/activity_component.html' %}
      
    </div>
  </main>

{% endblock %}

study_bud/core/templates/core/home_old.html
{% extends 'main.html'%};
{% block content %}
    
    <style>
        .home-container{
            display: grid;
            grid-template-columns: 1fr 3fr 1fr;
        }
    </style>
    <div class="home-container">
        {% include 'core/topics_component.html' %}

        <div>
            <a href="{% url 'core:create-room'%}">Create Room</a>
            <p>{{rooms_count}} Available</p>

            {% include 'core/feed_component.html' %} 
        </div>

        {% include 'core/activity_component.html'%}
    </div>

{% endblock %}

study_bud/core/templates/core/login_register.html
{% extends 'main.html'%};
{% block content %}
    
<main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Login</h3>
          </div>
        </div>
        <div class="layout__body">
          <h2 class="auth__tagline">Find your study partner</h2>
          {% if page == "login" %}
          <form class="form" action="" method="post">
            {% csrf_token %}
            
            <div class="form__group form__group">
              <label for="room_name">Username</label>
              <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy" />
            </div>
            <div class="form__group">
              <label for="password">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
              />
            </div>

            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>

              Login
            </button>
            
          </form>

          <div class="auth__action">
            <p>Haven't signed up yet?</p>
            <a href="{% url 'core:register' %}" class="btn btn--link">Sign Up</a>
          </div>
          {% else %}
          <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form__group">
                    <label for="room_{{field.label}}">{{field.label}}</label>
                    {{field}}
                  </div>
            {% endfor %}
            <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>
  
                Register
              </button>
          </form>
          <div class="auth__action">
             <p>Already signed up ?</p>
             <a href="{% url 'core:login' %}" class="btn btn--link">Login Up</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </main>

{% endblock %}

study_bud/core/templates/core/login_register_old.html
{% extends 'main.html'%};
{% block content %}

    {% if page == "login" %}
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username">
            <input type="password" name="password">
            <input type="submit" value="Log in">
        </form>
        <p>Haven't signed up yet ?</p>
        <a href="{% url 'core:register' %}">Sign up</a>
    </div>
    {% else %}
   <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Register">
        </form>
        <p>Alread signed up?</p>
        <a href="{% url 'core:login' %}">Log in</a>
   </div>
    {% endif %}
{% endblock %}

study_bud/core/templates/core/profile.html
{% extends 'main.html'%};
{% block content %}
<main class="profile-page layout layout--3">
    <div class="container">
      {% include 'core/topics_component.html'}%

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="https://randomuser.me/api/portraits/men/11.jpg" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{user.username}}</h3>
            <p>@{{user.username}}</p>
            {% if request.user.id == user.id%}
            <a href="{% url 'core:user-edit' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif%}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo tenetur
              facilis sunt nemo debitis quisquam hic atque aut? Ducimus alias placeat optio
              accusamus repudiandae quis ab ex exercitationem rem?
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by dennis_ivy</a>
            </h2>
          </div>
        </div>
        {% include 'core/feed_component.html'%}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      <div class="activities">
        <div class="activities__header">
          <h2>Recent Activities</h2>
        </div>
        {% include 'core/activity_component.html'%}
      </div>
      <!-- Activities End -->
    </div>
  </main>
{% endblock %}

study_bud/core/templates/core/room.html
{% extends 'main.html'%};
{% block content %}

    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'core:home'%}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>
            
            {% if request.user == room.host %}  
            <div class="room__topRight">
              
              <a href="{% url 'core:edit-room' room.id%}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'core:delete-room' room.id%}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
              
            </div>
            {% endif %}

          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{room.name}}</h3>
                <span>{{room.created | timesince}} days ago</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'core:user-profile' room.host.id%}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                  </div>
                  <span>@{{room.host}}</span>
                </a>
              </div>
              <!-- <div class="room__details">
                {{room.description}}
              </div> -->
              <span class="room__topics">{{room.topic.name}}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in room_messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'core:user-profile' message.user.id%}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                        </div>
                        <span>@{{message.user.username}}</span>
                      </a>
                      <span class="thread__date">{{message.created | timesince}} day ago</span>
                    </div>
                    {% if request.user == message.user%}
                    <a href="{% url 'core:delete-message' message.id %}">
                        <div class="thread__delete">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                              <title>remove</title>
                              <path
                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                              ></path>
                            </svg>
                          </div>
                    </a>
                    {% endif %} 
                  </div>
                  <div class="thread__details">
                    {{message.body}}
                  </div>
                </div>
                {% endfor %}   
              </div>
            </div>
          </div>
          <div class="room__message">
            <form action="" method="post">
                {% csrf_token %}
                <input name="body" placeholder="Write your message here..." />
            </form>
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
          <div class="participants__list scroll">
            {% for participant in participants %}
            <a href="{% url 'core:user-profile' participant.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="https://randomuser.me/api/portraits/men/37.jpg" />
              </div>
              <p>
                {{participant.username}}
                <span>@{{participant.username}}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
    <script src="script.js"></script>
{% endblock %}